import { Game, FeaturedGame } from "./types";

// This would be replaced with actual API calls in production
const gamesData: Game[] = [
  {
    id: "1",
    title: "2048",
    slug: "2048",
    description:
      "Join the numbers and get to the 2048 tile! A challenging number puzzle game that's easy to learn but hard to master.",
    imageUrl: "/images/games/2048.jpg",
    gameUrl: "/api/game-files/2048/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.8,
    playCount: 1500000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-03-15",
  },
  {
    id: "2",
    title: "A Dark Room",
    slug: "a-dark-room",
    description:
      "A minimalist text adventure game with deep storytelling and strategic resource management.",
    imageUrl: "/images/games/adarkroom.jpg",
    gameUrl: "/api/game-files/adarkroom/index.html",
    category: "Adventure",
    categorySlug: "adventure",
    rating: 4.9,
    playCount: 1200000,
    isNew: true,
    isFeatured: true,
    releaseDate: "2022-01-20",
  },
  {
    id: "3",
    title: "ASCII Space",
    slug: "asciispace",
    description:
      "Navigate through space using ASCII graphics in this retro-style space shooter.",
    imageUrl: "/images/games/asciispace.jpg",
    gameUrl: "/api/game-files/asciispace/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.5,
    playCount: 850000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-07-12",
  },
  {
    id: "4",
    title: "Asteroids",
    slug: "asteroids",
    description:
      "Classic arcade game where you control a spaceship and destroy asteroids while avoiding collisions.",
    imageUrl: "/images/games/asteroids.jpg",
    gameUrl: "/api/game-files/asteroids/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.7,
    playCount: 1800000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-02-18",
  },
  {
    id: "5",
    title: "Astray",
    slug: "astray",
    description:
      "Navigate through challenging 3D mazes in this beautiful puzzle game.",
    imageUrl: "/images/games/astray.jpg",
    gameUrl: "/api/game-files/astray/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.6,
    playCount: 950000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-09-10",
  },
  {
    id: "6",
    title: "Backcountry",
    slug: "backcountry",
    description:
      "Explore the wilderness and survive the challenges of nature in this outdoor adventure game.",
    imageUrl: "/images/games/backcountry.jpg",
    gameUrl: "/api/game-files/backcountry/index.html",
    category: "Adventure",
    categorySlug: "adventure",
    rating: 4.5,
    playCount: 780000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-11-05",
  },
  {
    id: "7",
    title: "Black Hole Square",
    slug: "blackholesquare",
    description:
      "A mind-bending puzzle game where you manipulate gravity and black holes to solve challenges.",
    imageUrl: "/images/games/blackholesquare.jpg",
    gameUrl: "/api/game-files/blackholesquare/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.7,
    playCount: 890000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-08-14",
  },
  {
    id: "8",
    title: "Bounce Back",
    slug: "bounceback",
    description:
      "Test your reflexes in this fast-paced ball-bouncing arcade game.",
    imageUrl: "/images/games/bounceback.jpg",
    gameUrl: "/api/game-files/bounceback/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.4,
    playCount: 720000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2021-01-22",
  },
  {
    id: "9",
    title: "Break Lock",
    slug: "breaklock",
    description:
      "A hybrid of Mastermind and the Android pattern lock, test your code-breaking skills.",
    imageUrl: "/images/games/breaklock.jpg",
    gameUrl: "/api/game-files/breaklock/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.5,
    playCount: 680000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-11-19",
  },
  {
    id: "10",
    title: "Breakout",
    slug: "breakout",
    description:
      "Classic brick-breaking arcade game where you bounce a ball to destroy all the bricks.",
    imageUrl: "/images/games/breakout.jpg",
    gameUrl: "/api/game-files/breakout/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.6,
    playCount: 2100000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-01-10",
  },
  {
    id: "11",
    title: "Captain Callisto",
    slug: "captaincallisto",
    description:
      "Help Captain Callisto navigate through space and complete challenging missions.",
    imageUrl: "/images/games/captaincallisto.jpg",
    gameUrl: "/api/game-files/captaincallisto/index.html",
    category: "Action",
    categorySlug: "action",
    rating: 4.4,
    playCount: 650000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2021-02-05",
  },
  {
    id: "12",
    title: "Chess",
    slug: "chess",
    description:
      "The classic game of chess with multiple difficulty levels and play modes.",
    imageUrl: "/images/games/chess.jpg",
    gameUrl: "/api/game-files/chess/index.html",
    category: "Strategy",
    categorySlug: "strategy",
    rating: 4.8,
    playCount: 1950000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-04-22",
  },
  {
    id: "13",
    title: "Chroma Incident",
    slug: "chromaincident",
    description:
      "A color-based puzzle game that challenges your perception and problem-solving skills.",
    imageUrl: "/images/games/chromaincident.jpg",
    gameUrl: "/api/game-files/chromaincident/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.5,
    playCount: 720000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2021-01-15",
  },
  {
    id: "14",
    title: "Chrome Dino",
    slug: "chromedino",
    description:
      "The famous T-Rex runner game from Chrome's offline page - jump over cacti and avoid obstacles.",
    imageUrl: "/images/games/chromedino.jpg",
    gameUrl: "/api/game-files/chromedino/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.7,
    playCount: 3200000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-01-05",
  },
  {
    id: "15",
    title: "Connect 3",
    slug: "connect3",
    description:
      "Match three or more of the same colored gems to score points in this addictive puzzle game.",
    imageUrl: "/images/games/connect3.jpg",
    gameUrl: "/api/game-files/connect3/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.5,
    playCount: 1400000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-06-30",
  },
  {
    id: "16",
    title: "Cookie Clicker",
    slug: "cookieclicker",
    description:
      "The addictive idle game where you bake cookies by clicking and upgrading your production.",
    imageUrl: "/images/games/cookieclicker.jpg",
    gameUrl: "/api/game-files/cookieclicker/index.html",
    category: "Idle",
    categorySlug: "idle",
    rating: 4.9,
    playCount: 4500000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-03-01",
  },
  {
    id: "17",
    title: "Edge Not Found",
    slug: "edgenotfound",
    description:
      "Navigate through a world where the edges of reality are missing in this unique puzzle platformer.",
    imageUrl: "/images/games/edgenotfound.jpg",
    gameUrl: "/api/game-files/edgenotfound/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.6,
    playCount: 750000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2021-04-10",
  },
  {
    id: "18",
    title: "Evil Glitch",
    slug: "evilglitch",
    description:
      "Battle against corrupted code in this retro-style action game with glitch-inspired mechanics.",
    imageUrl: "/images/games/evilglitch.jpg",
    gameUrl: "/api/game-files/evilglitch/index.html",
    category: "Action",
    categorySlug: "action",
    rating: 4.4,
    playCount: 680000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2021-03-15",
  },
  {
    id: "19",
    title: "Factory Balls Forever",
    slug: "factoryballsforever",
    description:
      "Paint and decorate balls according to patterns in this creative puzzle game.",
    imageUrl: "/images/games/factoryballsforever.jpg",
    gameUrl: "/api/game-files/factoryballsforever/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.7,
    playCount: 890000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-09-28",
  },
  {
    id: "20",
    title: "Flappy Bird",
    slug: "flappybird",
    description:
      "Navigate a bird through obstacles by tapping to flap its wings in this famously difficult game.",
    imageUrl: "/images/games/flappybird.jpg",
    gameUrl: "/api/game-files/flappybird/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.7,
    playCount: 5200000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-01-15",
  },
  {
    id: "21",
    title: "Geometry Dash",
    slug: "geometrydash",
    description:
      "Rhythm-based action platformer with simple one-touch gameplay and challenging levels.",
    imageUrl: "/images/games/geometrydash.jpg",
    gameUrl: "/api/game-files/geometrydash/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.8,
    playCount: 2800000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-05-12",
  },
  {
    id: "22",
    title: "Hextris",
    slug: "hextris",
    description:
      "A fast-paced puzzle game where you rotate a hexagon to prevent blocks from building up.",
    imageUrl: "/images/games/hextris.jpg",
    gameUrl: "/api/game-files/hextris/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.6,
    playCount: 1100000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-08-08",
  },
  {
    id: "23",
    title: "Konnekt",
    slug: "konnekt",
    description:
      "Connect all the dots without crossing paths in this challenging puzzle game.",
    imageUrl: "/images/games/konnekt.jpg",
    gameUrl: "/api/game-files/konnekt/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.5,
    playCount: 720000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2021-02-17",
  },
  {
    id: "24",
    title: "Minecraft Classic",
    slug: "minecraft",
    description:
      "Build anything you can imagine in this browser version of the classic creative building game.",
    imageUrl: "/images/games/minecraft.jpg",
    gameUrl: "/api/game-files/minecraft/index.html",
    category: "Adventure",
    categorySlug: "adventure",
    rating: 4.9,
    playCount: 6500000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-02-01",
  },
  {
    id: "25",
    title: "Ninja vs Evil Corp",
    slug: "ninjavsevilcorp",
    description:
      "Help the ninja defeat the evil corporation by solving puzzles and defeating enemies.",
    imageUrl: "/images/games/ninjavsevilcorp.jpg",
    gameUrl: "/api/game-files/ninjavsevilcorp/index.html",
    category: "Action",
    categorySlug: "action",
    rating: 4.5,
    playCount: 890000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-11-21",
  },
  {
    id: "26",
    title: "Pack-a-Bunch-a",
    slug: "packabunchas",
    description:
      "Pack and arrange objects to fit into limited space in this spatial puzzle game.",
    imageUrl: "/images/games/packabunchas.jpg",
    gameUrl: "/api/game-files/packabunchas/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.4,
    playCount: 680000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2021-01-05",
  },
  {
    id: "27",
    title: "Pac-Man",
    slug: "pacman",
    description:
      "Navigate Pac-Man through a maze, eating dots and avoiding ghosts in this arcade classic.",
    imageUrl: "/images/games/pacman.jpg",
    gameUrl: "/api/game-files/pacman/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.9,
    playCount: 4200000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-01-08",
  },
  {
    id: "28",
    title: "Particle Clicker",
    slug: "particleclicker",
    description:
      "Discover particles and advance scientific research in this idle physics game.",
    imageUrl: "/images/games/particleclicker.jpg",
    gameUrl: "/api/game-files/particleclicker/index.html",
    category: "Idle",
    categorySlug: "idle",
    rating: 4.6,
    playCount: 1100000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-07-30",
  },
  {
    id: "29",
    title: "Push Back",
    slug: "pushback",
    description:
      "Push blocks to solve puzzles and advance through increasingly challenging levels.",
    imageUrl: "/images/games/pushback.jpg",
    gameUrl: "/api/game-files/pushback/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.5,
    playCount: 750000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-10-15",
  },
  {
    id: "30",
    title: "Q1K3",
    slug: "q1k3",
    description:
      "A minimalist first-person shooter inspired by classic 90s games but with modern gameplay.",
    imageUrl: "/images/games/q1k3.jpg",
    gameUrl: "/api/game-files/q1k3/index.html",
    category: "Action",
    categorySlug: "action",
    rating: 4.7,
    playCount: 1300000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-12-08",
  },
  {
    id: "31",
    title: "Racer",
    slug: "racer",
    description:
      "Test your driving skills in this fast-paced racing game with multiple tracks and vehicles.",
    imageUrl: "/images/games/racer.jpg",
    gameUrl: "/api/game-files/racer/index.html",
    category: "Racing",
    categorySlug: "racing",
    rating: 4.6,
    playCount: 1800000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-06-12",
  },
  {
    id: "32",
    title: "Radius Raid",
    slug: "radiusraid",
    description:
      "Defend against waves of enemies in this circular space shooter game.",
    imageUrl: "/images/games/radiusraid.jpg",
    gameUrl: "/api/game-files/radiusraid/index.html",
    category: "Action",
    categorySlug: "action",
    rating: 4.5,
    playCount: 920000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-09-05",
  },
  {
    id: "33",
    title: "Retro Haunt",
    slug: "retrohaunt",
    description:
      "Explore a haunted environment with retro-style graphics and atmospheric gameplay.",
    imageUrl: "/images/games/retrohaunt.jpg",
    gameUrl: "/api/game-files/retrohaunt/index.html",
    category: "Adventure",
    categorySlug: "adventure",
    rating: 4.6,
    playCount: 780000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-10-28",
  },
  {
    id: "34",
    title: "Road Blocks",
    slug: "roadblocks",
    description:
      "Navigate through a road full of blocks and obstacles in this challenging driving game.",
    imageUrl: "/images/games/roadblocks.jpg",
    gameUrl: "/api/game-files/roadblocks/index.html",
    category: "Racing",
    categorySlug: "racing",
    rating: 4.4,
    playCount: 850000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-11-12",
  },
  {
    id: "35",
    title: "Run 3",
    slug: "run3",
    description:
      "Run and jump through space tunnels, avoiding gaps and collecting coins.",
    imageUrl: "/images/games/run3.jpg",
    gameUrl: "/api/game-files/run3/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.8,
    playCount: 3100000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-04-05",
  },
  {
    id: "36",
    title: "Shuttle Deck",
    slug: "shuttledeck",
    description:
      "Manage a space shuttle's operations and keep the crew safe in this management simulation.",
    imageUrl: "/images/games/shuttledeck.jpg",
    gameUrl: "/api/game-files/shuttledeck/index.html",
    category: "Simulation",
    categorySlug: "simulation",
    rating: 4.5,
    playCount: 680000,
    isNew: true,
    isFeatured: false,
    releaseDate: "2022-02-15",
  },
  {
    id: "37",
    title: "Sleeping Beauty",
    slug: "sleepingbeauty",
    description:
      "Help the sleeping beauty navigate her dreams in this dreamy adventure game.",
    imageUrl: "/images/games/sleepingbeauty.jpg",
    gameUrl: "/api/game-files/sleepingbeauty/index.html",
    category: "Adventure",
    categorySlug: "adventure",
    rating: 4.6,
    playCount: 750000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-12-20",
  },
  {
    id: "38",
    title: "Snake",
    slug: "snake",
    description:
      "Classic snake game where you grow by eating food and avoid hitting walls or yourself.",
    imageUrl: "/images/games/snake.jpg",
    gameUrl: "/api/game-files/snake/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.6,
    playCount: 2800000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-01-20",
  },
  {
    id: "39",
    title: "Space Company",
    slug: "spacecompany",
    description:
      "Build your space company from the ground up, managing resources and expanding your reach.",
    imageUrl: "/images/games/spacecompany.jpg",
    gameUrl: "/api/game-files/spacecompany/index.html",
    category: "Idle",
    categorySlug: "idle",
    rating: 4.7,
    playCount: 1400000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-08-25",
  },
  {
    id: "40",
    title: "Space Garden",
    slug: "spacegarden",
    description:
      "Grow and tend to plants in space in this relaxing gardening simulation.",
    imageUrl: "/images/games/spacegarden.jpg",
    gameUrl: "/api/game-files/spacegarden/index.html",
    category: "Simulation",
    categorySlug: "simulation",
    rating: 4.5,
    playCount: 650000,
    isNew: true,
    isFeatured: false,
    releaseDate: "2022-01-18",
  },
  {
    id: "41",
    title: "Space Huggers",
    slug: "spacehuggers",
    description:
      "Defend Earth from alien invaders in this space-themed shooter game.",
    imageUrl: "/images/games/spacehuggers.jpg",
    gameUrl: "/api/game-files/spacehuggers/index.html",
    category: "Action",
    categorySlug: "action",
    rating: 4.6,
    playCount: 950000,
    isNew: true,
    isFeatured: false,
    releaseDate: "2022-02-05",
  },
  {
    id: "42",
    title: "Tetris",
    slug: "tetris",
    description:
      "Arrange falling blocks to create complete rows in this timeless puzzle game.",
    imageUrl: "/images/games/tetris.jpg",
    gameUrl: "/api/game-files/tetris/index.html",
    category: "Puzzle",
    categorySlug: "puzzle",
    rating: 4.9,
    playCount: 5800000,
    isNew: false,
    isFeatured: true,
    releaseDate: "2020-01-12",
  },
  {
    id: "43",
    title: "The Maze of Space Goblins",
    slug: "themazeofspacegoblins",
    description:
      "Navigate through a maze filled with space goblins in this adventure puzzle game.",
    imageUrl: "/images/games/themazeofspacegoblins.jpg",
    gameUrl: "/api/game-files/themazeofspacegoblins/index.html",
    category: "Adventure",
    categorySlug: "adventure",
    rating: 4.5,
    playCount: 720000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2021-01-28",
  },
  {
    id: "44",
    title: "Tower Master",
    slug: "towermaster",
    description:
      "Stack blocks to build the tallest tower possible in this physics-based challenge.",
    imageUrl: "/images/games/towermaster.jpg",
    gameUrl: "/api/game-files/towermaster/index.html",
    category: "Arcade",
    categorySlug: "arcade",
    rating: 4.6,
    playCount: 1100000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-07-14",
  },
  {
    id: "45",
    title: "Trimps",
    slug: "trimps",
    description:
      "Lead your Trimps to victory through idle progression and strategic resource management.",
    imageUrl: "/images/games/trimps.jpg",
    gameUrl: "/api/game-files/trimps/index.html",
    category: "Idle",
    categorySlug: "idle",
    rating: 4.7,
    playCount: 1250000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-09-18",
  },
  {
    id: "46",
    title: "Underrun",
    slug: "underrun",
    description:
      "Explore a digital underworld and fight against corrupted programs in this action game.",
    imageUrl: "/images/games/underrun.jpg",
    gameUrl: "/api/game-files/underrun/index.html",
    category: "Action",
    categorySlug: "action",
    rating: 4.6,
    playCount: 850000,
    isNew: false,
    isFeatured: false,
    releaseDate: "2020-11-05",
  },
  {
    id: "47",
    title: "XX142-b2.exe",
    slug: "xx142-b2exe",
    description:
      "A mysterious executable file that contains a hidden game with retro-inspired gameplay.",
    imageUrl: "/images/games/xx142-b2exe.jpg",
    gameUrl: "/api/game-files/xx142-b2exe/index.html",
    category: "Adventure",
    categorySlug: "adventure",
    rating: 4.7,
    playCount: 780000,
    isNew: true,
    isFeatured: false,
    releaseDate: "2022-01-10",
  },
];

export async function getGames(): Promise<Game[]> {
  // In production, you would fetch this from an API
  return gamesData;
}

export async function getGameBySlug(slug: string): Promise<Game | null> {
  return gamesData.find((game) => game.slug === slug) || null;
}

export async function getPopularGames(limit?: number): Promise<Game[]> {
  // Sort by play count and limit if needed
  const sortedGames = [...gamesData].sort((a, b) => b.playCount - a.playCount);
  return limit ? sortedGames.slice(0, limit) : sortedGames;
}

export async function getNewGames(limit?: number): Promise<Game[]> {
  // Sort by release date and limit if needed
  const sortedGames = [...gamesData].sort(
    (a, b) =>
      new Date(b.releaseDate).getTime() - new Date(a.releaseDate).getTime()
  );
  return limit ? sortedGames.slice(0, limit) : sortedGames;
}

export async function getFeaturedGames(): Promise<FeaturedGame[]> {
  return gamesData
    .filter((game) => game.isFeatured)
    .map((game) => ({
      ...game,
      highlightText: "Featured Game",
    }));
}

export async function getGamesByCategory(
  categorySlug: string
): Promise<Game[]> {
  return gamesData.filter((game) => game.categorySlug === categorySlug);
}

export async function searchGames(query: string): Promise<Game[]> {
  const searchTerm = query.toLowerCase();
  return gamesData.filter(
    (game) =>
      game.title.toLowerCase().includes(searchTerm) ||
      game.description.toLowerCase().includes(searchTerm) ||
      game.category.toLowerCase().includes(searchTerm)
  );
}
